version: "3.2"

services:
  commune:
    network_mode: host
    container_name: commune
    build: ./
    shm_size: '20gb'
    environment:
      - LOCAL_SUBTENSOR_HOST=node-subtensor
      - RAY_PORT=6378
    volumes:
      # BITTENSOR
      - ./bittensor/bittensor:/app/bittensor/bittensor
      - ~/.bittensor:/root/.bittensor
      - ./bittensor/tests:/app/bittensor/tests

      # COMMUNE MOUNTS
      - ./commune:/app/commune
      - ./contracts:/app/contracts
      - ./interfaces:/app/interfaces
      - ./artifacts:/app/artifacts

      - ./cortex/cortex:/app/cortex
      # - ./ocean.py/ocean_lib:/app/ocean.py/ocean_lib

      # OTHER MOUNTS
      - ./scripts:/app/scripts
      - /tmp:/tmp # TMP FILE SYSTEM MOUNT
      - /home/ubuntu/efs:/efs
      - /usr/local/cuda/bin/nvcc:/usr/local/cuda/bin/nvcc 

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    command: bash -c "cd /app; chmod +x /app/scripts/*;/app/scripts/startup.sh;"

  
